export const compatibilityFixtureUrl = new URL('../vault/', import.meta.url);

export const compatibilityFixtureFiles = [
  'Home.md',
  'Root.md',
  'Simple.md',
  'Folders/Alpha.md',
  'Folders/Beta.md',
  'Duplicate/A/Shared.md',
  'Duplicate/B/Shared.md',
  'Links/Aliases.md',
  'Links/Blocks.md',
  'Links/Embeds.md',
  'Links/Headings.md',
  'Links/Unresolved.md',
  'Markdown/Callouts.md',
  'Markdown/Code.md',
  'Markdown/Frontmatter.md',
  'Markdown/Math.md',
  'Markdown/Tables.md',
  'Markdown/Tags.md',
  'Markdown/Tasks.md',
  'Notes/Project Alpha.md',
  'Notes/Referenced Note.md',
  'Notes/Unresolved Links.md',
  'Unicode/Café.md',
  'Unicode/日本語.md',
  'Unicode/Spaces in name.md',
  'Attachments/image.png',
  'Attachments/pixel.png',
  'Attachments/sample.pdf',
] as const;
